#!/bin/bash
if [ $1 = "sleep" ]; then
 activator send libactivator.system.sleepbutton
 echo Power button press simulated.
fi
if [ $1 = "home" ]; then
 activator send libactivator.system.homebutton
 echo Home button press simulated.
fi
if [ $1 = "open" ]; then
 activator send $2
 echo App opened.
fi
if [ $1 = "settings" ]; then
 activator send libactivator.settings.$2
 echo Preference page opened.
fi
if [ $1 = "cc" ]; then
 activator send libactivator.system.activate-control-center
echo Control Center opened.
fi
if [ $1 = "screenshot" ]; then
 activator send libactivator.system.take-screenshot
 echo Screenshot saved in gallery.
fi
if [ $1 = "vol" ]; then
 activator send libactivator.audio.$2-volume
 echo Volume changed
fi
if [ $1 = "brightness" ]; then
 activator send libactivator.screen.brightness.$2
 echo Brightness changed
fi
if [ $1 = "switcher" ]; then
 activator send libactivator.system.activate-switcher
 echo Switcher activated.
fi
if [ $1 = "nc" ]; then
 activator send libactivator.system.activate-notification-center
 echo Notification Center opened.
fi
if [ $1 = "answer" ]; then
 activator send libactivator.phone.answer-call
 echo Call answered.
fi
if [ $1 = "decline" ]; then
 activator send libactivator.phone.disconnect-call
 echo Call declined.
fi
if [ $1 = "first-homepage" ]; then
 activator send libactivator.system.first-springboard-page
 echo First homescreen page opened.
fi
if [ $1 = "power-menu" ]; then
 activator send libactivator.system.power-menu
 echo Power menu opened.
fi
if [ $1 = "siri" ]; then
 activator send libactivator.system.virtual-assistant
 echo Siri opened.
fi
if [ $1 = "clear-switcher" ]; then
 activator send libactivator.system.clear-switcher
 echo App Switcher cleared.
fi
if [ $1 = "spotlight" ]; then
 activator send libactivator.system.spotlight
 echo Spotlight opened.
fi
if [ $1 = "powerdown" ]; then
 activator send libactivator.system.powerdown
 echo Device turned off.
fi
if [ $1 = "help" ]; then
 echo Usage: nimbus action
 echo List of actions:
 echo sleep - simulate power button press.
 echo home - simulate homebutton press.
 echo open app.bundle.id - open app with specified bundle ID.
 echo settings preference panel name - open specified preference panel in settings.
 echo cc - open Control Center.
 echo screenshot - make a screenshot.
 echo vol/brightness increase/decrease - increase or decrease audio or brightness
 echo switcher - opens app switcher.
 echo nc - opens Notification Center.
 echo answer or decline - answer or decline a call - ex. answer-call.
 echo first-homepage - opens first srpingboard page.
 echo power-menu - opens the power menu.
 echo siri - opens Siri.
 echo clear-swither - close all apps from the app switcher.
 echo spotlight - opens Spotlight.
 echo powerdown - turns off the device.
 echo respring - resprings
 echo safemode - enters safe mode
 echo tone ringtone - plays ringtone on phone 
 echo tone-text ringtone - plays text tone on phone 
 echo vpn on/off - activates vpn 
 echo torch - turns torch on/off
 echo ringer on/off - turns ringer on
 echo hotspot on/off - turns mobile hotspot on
 echo unlock - unlocks device, requires com.giorgioiavicoli.passby
fi
if [ $1 = "respring" ]; then
 activator send libactivator.system.respring
 echo respringing
fi
if [ $1 = "safemode" ]; then
 activator send libactivator.system.safemode
 echo respringing into safe mode
fi
if [ $1 = "tone" ]; then
 activator send libactivator.ringtone.system:Marimba
fi
if [ $1 = "tone" ]; then
 activator send libactivator.ringtone.system:$2    
 echo PLaying ringtone $2
fi
if [ $1 = "tone-text" ]; then
 activator send libactivator.ringtone.texttone:$2   
 echo PLaying ringtone $2
fi
if [ $1 = "vpn" ]; then
 activator send switch-$2.com.a3tweaks.switch.vpn
 echo turning vpn $2 
fi
if [ $1 = "torch" ]; then
 activator send switch-flip.com.a3tweaks.switch.flashlight
 echo Turning torch on/off
fi
if [ $1 = "ringer" ]; then
 activator send switch-$2.com.a3tweaks.switch.ringer
 echo Turning ringer $2
fi
if [ $1 = "hotspot" ]; then
 activator send switch-$2.com.a3tweaks.switch.hotspot
 echo Turning mobile hotspot $2
fi
if [ $1 = "unlock" ]; then
 activator send com.giorgioiavicoli.passby.unlock
 echo Unlocking device
fi
if [ -z $1 ]; then
 echo You must specify a command, type "nimbus help" for a list of commands
fi
